# Numpy Assignment2

In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

In [2]:
#1.Choose a value and set the variable x to that value

In [1]:
x=4
print(x)

4


In [2]:
#2

In [6]:
x1=x**2
print(x1)

16


In [7]:
x2=x**3
print(x2)

64


In [8]:
#3

In [9]:
import numpy as np

In [10]:
z=([2,4,7,8])
print(z)

[2, 4, 7, 8]


In [11]:
np.angle(z,deg=0)

array([0., 0., 0., 0.])

In [12]:
#4

In [13]:
np.cos(z)

array([-0.41614684, -0.65364362,  0.75390225, -0.14550003])

In [14]:
np.sin(z)

array([ 0.90929743, -0.7568025 ,  0.6569866 ,  0.98935825])

In [15]:
#5

In [16]:
f=np.arange(1,501)
print(f)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [17]:
Y=np.linspace(f,500)
print(Y)

[[  1.           2.           3.         ... 498.         499.
  500.        ]
 [ 11.18367347  12.16326531  13.14285714 ... 498.04081633 499.02040816
  500.        ]
 [ 21.36734694  22.32653061  23.28571429 ... 498.08163265 499.04081633
  500.        ]
 ...
 [479.63265306 479.67346939 479.71428571 ... 499.91836735 499.95918367
  500.        ]
 [489.81632653 489.83673469 489.85714286 ... 499.95918367 499.97959184
  500.        ]
 [500.         500.         500.         ... 500.         500.
  500.        ]]


In [18]:
#6

In [21]:
z=np.linspace(Y,53)
print(z)

[[[  1.           2.           3.         ... 498.         499.
   500.        ]
  [ 11.18367347  12.16326531  13.14285714 ... 498.04081633 499.02040816
   500.        ]
  [ 21.36734694  22.32653061  23.28571429 ... 498.08163265 499.04081633
   500.        ]
  ...
  [479.63265306 479.67346939 479.71428571 ... 499.91836735 499.95918367
   500.        ]
  [489.81632653 489.83673469 489.85714286 ... 499.95918367 499.97959184
   500.        ]
  [500.         500.         500.         ... 500.         500.
   500.        ]]

 [[  2.06122449   3.04081633   4.02040816 ... 488.91836735 489.89795918
   490.87755102]
  [ 12.03706789  12.99666805  13.95626822 ... 488.95835069 489.91795085
   490.87755102]
  [ 22.01291129  22.95251978  23.89212828 ... 488.99833403 489.93794252
   490.87755102]
  ...
  [470.92586422 470.96584756 471.0058309  ... 490.79758434 490.83756768
   490.87755102]
  [480.90170762 480.92169929 480.94169096 ... 490.83756768 490.85755935
   490.87755102]
  [490.87755102 490.877

# Exercise 2- Vector and Matrix operations

In [22]:
import numpy as np

In [23]:
#1

In [24]:
vec=np.array([-1.,4.,-9.])
mat1=np.array([[1.,3.,5.],[7.,-9.,2.],[4.,6.,8.]])

In [25]:
print(vec)

[-1.  4. -9.]


In [26]:
print(mat1)

[[ 1.  3.  5.]
 [ 7. -9.  2.]
 [ 4.  6.  8.]]


In [27]:
vec1=(4)*vec
vec1

array([ -4.,  16., -36.])

In [28]:
vec2=(np.pi/4)*vec

In [32]:
vec2=(np.pi%4)*vec

In [29]:
#2

In [31]:
vec3=np.cos(vec1)
vec3

array([-0.65364362, -0.95765948, -0.12796369])

In [33]:
vec4=np.cos(vec)
vec4

array([ 0.54030231, -0.65364362, -0.91113026])

In [34]:
#3

In [35]:
vec5=vec1+2*vec3
vec5

array([ -5.30728724,  14.08468104, -36.25592738])

In [42]:
#4

In [43]:
import euclidean norm as la.norm

SyntaxError: invalid syntax (<ipython-input-43-80d672ae2498>, line 1)

In [44]:
#5

In [45]:
print(mat1*vec)

[[ -1.  12. -45.]
 [ -7. -36. -18.]
 [ -4.  24. -72.]]


In [46]:
#6

In [47]:
mat1.transpose()

array([[ 1.,  7.,  4.],
       [ 3., -9.,  6.],
       [ 5.,  2.,  8.]])

In [48]:
#7

In [49]:
a=np.linalg.det(mat1)
a

161.99999999999994

In [50]:
#8

In [51]:
mat1.trace()

0.0

In [52]:
mat1.transpose().trace()

0.0

In [53]:
#9

In [55]:
vec_x=np.array([-1,4,-9])
vec_x

array([-1,  4, -9])

In [56]:
min=vec_x[0];

In [57]:
for i in range(0,len(vec_x)):
    if(vec_x[i]<min):
        min=vec_x[i];
        print("smallest element in vec_x="+str(min));

smallest element in vec_x=-9


In [58]:
#11

In [59]:
mat1.min()

-9.0

In [60]:
np.min(mat1)

-9.0