# Numpy Assignment 3

In [69]:
import numpy as np

In [134]:
#1.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 ... 7 8 9]


In [135]:
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 ... -1  8 -1]


In [136]:
#2.

In [137]:
import numpy as np
arr=np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [138]:
#3

In [144]:
arr=np.array([1,2,3])
np.r_[np.repeat(arr,3),np.tile(arr,3)]

array([1, 1, 1, ..., 1, 2, 3])

In [145]:
#4

In [146]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [147]:
print(np.intersect1d(a,b))

[2 4]


In [148]:
#5

In [149]:
a=np.array([1,2,3,2,3,4,3,4,5,6])


In [150]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [151]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [152]:
#6

In [153]:
print(np.random.rand(5,3))

[[0.575093 0.891322 0.209202]
 [0.185328 0.108377 0.219697]
 [0.978624 0.811683 0.171941]
 [0.816225 0.274074 0.431704]
 [0.94003  0.817649 0.336112]]


In [154]:
#7 How to limit the number of items printed in output of numpy array to 6?
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.


In [155]:
arr=np.arange(15)

In [156]:
np.set_printoptions(threshold=6)
print(arr)

[ 0  1  2 ... 12 13 14]


In [157]:
#8.How to pretty print a numpy array by suppressing the scientific notation (like 1el0)?
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [166]:
np.random.seed(100) 

In [167]:
rand_arr=np.random.random([3,3])/1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [160]:
np.set_printoptions(suppress=True) 
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [161]:
#9. How to swap two columns in a 2d numpy array?
#Swap columns 1 and 2 in the array arr.

In [162]:
arr=np.arange(9).reshape(3,3)

In [163]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [164]:
#10.  How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr:

In [165]:
arr=np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])