# Numpy Assignment 1

In [1]:
#1.Write a python program to take a 3X3 matrix as a user input. 
#Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix. 

In [3]:
import numpy as np
arr=np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(arr.ndim)

2


In [5]:
print(arr.shape)

(3, 3)


In [6]:
#2.Write a function that generates 10 integers and use it to build an array 

In [9]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
#3.Create a random vector (1D array) of size 10 and sort it 

In [53]:
x1 = np.random.randint(10, size=10)
print(x1)

[9 7 2 5 9 7 9 4 0 3]


In [54]:
x1.sort()

In [55]:
print(x1)

[0 2 3 4 5 7 7 9 9 9]


In [25]:
#4.Write a Python program to generate five random numbers from the normal distribution.


In [30]:
x2=np.random.normal(size=5)

In [31]:
print(x2)

[ 1.40443068 -0.13305897  0.2530302   0.6698048   1.46769217]


In [32]:
#5.Write a numpy program program to add and subtract two random matrices. 
#The size of the matrix will a user input. All the matrix element should be a positive integer value.
#Suppose 'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of
#'B' matrix cannot be greater than 20. 

In [70]:
A = np.random.randint(10, size=(2,2)) 
print(A)

[[7 0]
 [8 7]]


In [71]:
B= np.random.randint(20, size=(2,2)) 
print(B)

[[ 8 16]
 [ 4 17]]


In [72]:
c=np.add(A,B)
print(c)

[[15 16]
 [12 24]]


In [75]:
d=np.subtract(A,B)
print(d)

[[ -1 -16]
 [  4 -10]]


In [76]:
#6.

In [87]:
A = np.random.randint(10, size=(1,2)) 
print(A)

[[0 0]]


In [92]:
B= np.random.randint(10, size=(2,3)) 
print(B)

[[2 8 2]
 [0 6 8]]


In [93]:
c=np.multiply(A,B)
print(c)

ValueError: operands could not be broadcast together with shapes (1,2) (2,3) 